import raw from "./catalog.json";
import type { Profile } from "./types";

// The entity library: every item a baby and a mother normally need, by stage, pregnancy included.
// Generated by scripts/build-catalog.mjs (Claude, one call per stage) and reviewed by hand. Stable `id` across stages.
export type Category = "diapers" | "feeding" | "solids" | "feeding_gear" | "clothing" | "sleep" | "bath_care" | "health" | "safety" | "gear" | "play" | "books" | "mom" | "outings";
export type Kind = "monthly" | "one_time" | "occasional";
export type Item = {
  id: string; label_en: string; label_zh: string; category: Category; tier: 1 | 2 | 3; kind: Kind; cost: number;
  qty_en: string; qty_zh: string; cheap_en: string; cheap_zh: string; only: "any" | "breastfeeding" | "formula"; essential: boolean;
  stage: string; from: number; to: number;
};
export const CATALOG = raw as Item[];

export function itemsForMonths(months: number, profile: Profile): Item[] {
  const formula = profile.formula_ml_per_day > 0;
  return CATALOG.filter((it) => months >= it.from && months <= it.to).filter((it) => it.only === "any" || (it.only === "formula" ? formula : !formula));
}

export function findItem(id: string, months: number): Item | undefined {
  return CATALOG.find((it) => it.id === id && months >= it.from && months <= it.to) ?? CATALOG.find((it) => it.id === id);
}

// Monthly equivalent used for budget math: occasional items are spread over the stage.
export function monthlyCost(it: Item): number {
  if (it.kind === "monthly") return it.cost;
  if (it.kind === "occasional") return Math.round((it.cost / 3) * 10) / 10;
  return 0; // one-time items are shown separately
}
